export const projectColors = [
  { name: "Calm Blue", value: "#5B8DEF" },
  { name: "Soft Indigo", value: "#7C83FD" },
  { name: "Lavender", value: "#A78BFA" },
  { name: "Orchid", value: "#C084FC" },
  { name: "Soft Pink", value: "#F472B6" },
  { name: "Rose", value: "#FB7185" },
  { name: "Coral", value: "#F87171" },
  { name: "Peach", value: "#FB923C" },
  { name: "Amber", value: "#F59E0B" },
  { name: "Honey", value: "#EAB308" },
  { name: "Lime", value: "#84CC16" },
  { name: "Fresh Green", value: "#22C55E" },
  { name: "Mint", value: "#34D399" },
  { name: "Seafoam", value: "#2DD4BF" },
  { name: "Aqua", value: "#22D3EE" },
  { name: "Sky", value: "#38BDF8" },
  { name: "Ocean", value: "#0EA5E9" },
  { name: "Steel Blue", value: "#64748B" },
  { name: "Slate Violet", value: "#6D6AF2" },
  { name: "Periwinkle", value: "#818CF8" },
  { name: "Soft Grape", value: "#A855F7" },
  { name: "Magenta", value: "#D946EF" },
  { name: "Watermelon", value: "#F43F5E" },
  { name: "Apricot", value: "#F97316" },
  { name: "Gold", value: "#D97706" },
  { name: "Meadow", value: "#16A34A" },
  { name: "Emerald", value: "#10B981" },
  { name: "Teal", value: "#14B8A6" },
  { name: "Cyan", value: "#06B6D4" },
  { name: "Royal Blue", value: "#3B82F6" },
];
